exec_once:
 files:
  /tmp/discourse.conf:
    name: discourse.conf
    path: /tmp/
    mode: "0644"
    owner: root
    group: root
    content: |
      templates:
        - "templates/postgres.template.yml"
        - "templates/redis.template.yml"
        - "templates/web.template.yml"
        - "templates/web.ratelimited.template.yml"
      ## Uncomment these two lines if you wish to add Lets Encrypt (https)
        #- "templates/web.ssl.template.yml"
        #- "templates/web.letsencrypt.ssl.template.yml"
      expose:
        - "80:80"   # http
        - "443:443" # https
      
      params:
        db_default_text_search_config: "pg_catalog.english"
      
        db_shared_buffers:
      
      env:
        LANG: en_US.UTF-8
        # DISCOURSE_DEFAULT_LOCALE: en
      
        UNICORN_WORKERS:
      
        ## The domain name this Discourse instance will respond to
        DISCOURSE_HOSTNAME: DISCOURSE_HOSTNAME_VAR
      
        DISCOURSE_DEVELOPER_EMAILS: 'DISCOURSE_EMAIL_VAR'
      
        DISCOURSE_SMTP_ADDRESS: DISCOURSE_SMTP_ADDRESS_VAR
        DISCOURSE_SMTP_PORT: DISCOURSE_SMTP_PORT_VAR
        DISCOURSE_SMTP_USER_NAME: DISCOURSE_SMTP_USER_NAME_VAR
        DISCOURSE_SMTP_PASSWORD: "DISCOURSE_SMTP_PASSWORD_VAR"
        #DISCOURSE_SMTP_ENABLE_START_TLS: true           # (optional, default true)
      
        ## If you added the Lets Encrypt template, uncomment below to get a free SSL certificate
        #LETSENCRYPT_ACCOUNT_EMAIL: me@example.com
      
        ## The CDN address for this Discourse instance (configured to pull)
        ## see https://meta.discourse.org/t/14857 for details
        #DISCOURSE_CDN_URL: //discourse-cdn.example.com
      
      ## The Docker container is stateless; all data is stored in /shared
      volumes:
        - volume:
            host: /var/discourse/shared/standalone
            guest: /shared
        - volume:
            host: /var/discourse/shared/standalone/log/var-log
            guest: /var/log
      
      ## Plugins go here
      ## see https://meta.discourse.org/t/19157 for details
      hooks:
        after_code:
          - exec:
              cd: $home/plugins
              cmd:
                - git clone https://github.com/discourse/docker_manager.git
      
      ## Any custom commands to run after building
      run:
        - exec: echo "Beginning of custom commands"
        ## If you want to set the 'From' email address for your first registration, uncomment and change:
        ## After getting the first signup email, re-comment the line. It only needs to run once.
        #- exec: rails r "SiteSetting.notification_email='info@unconfigured.discourse.org'"
        - exec: echo "End of custom commands"

 execs:
  Install Docker and Git:
   name: Install Docker and Git
   command: |
     #!/usr/bin/env bash
     wget -qO- https://get.docker.com/ | sh

  Download Discourse:
   name: Download Discourse
   command: |
     #!/usr/bin/env bash
     discourse_dir='/var/discourse'
     mkdir -p  ${discourse_dir}
     if [ -z "$(ls -A ${discourse_dir})" ]; then
        git clone https://github.com/discourse/discourse_docker.git ${discourse_dir}
     fi

  Add Discourse Cofiguration:
   name: Add Discourse Configuration
   command: |
     #!/usr/bin/env bash
     . /etc/profile.d/azure_secrets.sh
     config_file_template='/tmp/discourse.conf'

     sed -i -- "s/DISCOURSE_HOSTNAME_VAR/${DISCOURSE_HOSTNAME}/g" ${config_file_template}
     sed -i -- "s/DISCOURSE_SMTP_ADDRESS_VAR/${DISCOURSE_SMTP_ADDRESS}/g" ${config_file_template}
     sed -i -- "s/DISCOURSE_SMTP_PORT_VAR/${DISCOURSE_SMTP_PORT}/g" ${config_file_template}
     sed -i -- "s/DISCOURSE_SMTP_USER_NAME_VAR/${DISCOURSE_SMTP_USER_NAME}/g" ${config_file_template}
     sed -i -- "s/DISCOURSE_SMTP_PASSWORD_VAR/${DISCOURSE_SMTP_PASSWORD}/g" ${config_file_template}
     sed -i -- "s/DISCOURSE_EMAIL_VAR/${DISCOURSE_EMAIL}/g" ${config_file_template}

     cp ${config_file_template} /var/discourse/containers/app.yml

pre_app_deploy:
 execs:
  Start Discourse:
   name: Start Discourse
   timeout: "3000"
   command: |
     #!/usr/bin/env bash
     cd /var/discourse
     echo '\n' | ./discourse-setup
